# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-16 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190119_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='townie',
            name='plans',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='townie',
            name='referral',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='townie',
            name='socials',
            field=models.TextField(blank=True, default=''),
        ),
    ]
