# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-07-16 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190716_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='townie',
            name='reviewed',
        ),
    ]
